# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: drvladb
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent.days: 14
          plugin_languages_recent.load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_licenses: yes
          plugin_licenses_legal: yes
          plugin_notable: yes
          plugin_screenshot: yes
          plugin_screenshot_background: yes
          plugin_screenshot_selector: body
          plugin_screenshot_title: Screenshot
          plugin_stock: yes
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          plugin_stock_symbol: GME
          plugin_stock_token: ${{ secrets.STOCK_TOKEN }} # RapidAPI Yahoo Finance token
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: current
